TZ 14: Add controllers
romakrnv/java-shareit pull request #1
Opened 2024-10-28 13:34 UTC by romakrnv

2024-10-29 13:21 UTC, z8q requested changes

2024-10-29 13:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    @NotEmpty
Тут только нужно учесть, что внутри [NotEmpty](https://jakarta.ee/specifications/bean-validation/3.0/apidocs/jakarta/validation/constraints/notempty) в описании
```
The annotated element must not be null nor empty.
```
то есть может состоять из пробелов

Можно применить [NotBlank](https://jakarta.ee/specifications/platform/9/apidocs/jakarta/validation/constraints/notblank),
он проверит на empty и на пробелы (состоит ли строка только из пробелов),
и еще проверит на null

Описание NotBlank
```
The annotated element must not be null and must contain at least one non-whitespace character. Accepts CharSequence.
```

2024-10-29 13:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/User.java
> +    @NotEmpty @Email
можно тоже поменять на NotBlank

2024-10-29 13:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +public class ItemService {
стоит учесть вот этот момент из тз
```
Также создайте интерфейс ItemService и реализующий его класс ItemServiceImpl, 
к которому будет обращаться ваш контроллер
```

2024-10-29 13:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDao.java
> +    }
потом надо не забыть реализовать)

2024-10-29 13:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto updateItem(@PathVariable Long id, @RequestBody Map<String, Object> updates,
Почему решил не использовать Item?
Возможно из-за того, что в Patch допускаются null значения в полях?
можно попробовать использовать без аннотации Valid

2024-10-29 13:27 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@Valid @RequestBody Item item, @RequestHeader("X-Sharer-User-Id") Long userId) {
Принимать нужно будет тоже dto вместо Item item
В последующих домашках у Item будет функционал работы с базами, а дто больше подойдет для "транспортных" операций (приема/отправки в контроллерах)

2024-10-29 17:06 UTC, romakrnv commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +public class ItemService {
Не совсем понял какой смысл в интерфейсе если у нас только лишь одна реализация для каждого сервиса
Обсудили это на мите, там подтвердили тоже самое
Но если там дальше имеет большой смысл, то могу конечно сделать, не проблема)

2024-10-29 19:07 UTC, romakrnv commented on src/main/java/ru/practicum/shareit/item/dao/InMemoryItemDao.java
> +    }
сразу добавил по некст тз)

2024-10-30 18:23 UTC, z8q approved these changes

2024-10-30 18:33 UTC, merged