TZ 15 done
romakrnv/java-shareit pull request #2
Opened 2024-12-08 16:26 UTC by romakrnv

2024-12-09 19:18 UTC, z8q requested changes

2024-12-09 19:18 UTC, z8q commented on src/main/resources/schema.sql
> +    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
можно тоже написать constaint в lower-case формате, как остальные

2024-12-09 19:18 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    private final ItemRepository itemRepository;
FieldDefaults применяются, можно убрать private final для полей

2024-12-09 19:18 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/entity/Item.java
> +    @ManyToOne(fetch = FetchType.LAZY)
Можно смотреть по коду, как идет работа с Item
Если есть обращения к полю User, то будет возникать дополнительный запрос к базе для подгрузки Lazy-сущности
Использование может быть оправдано, если между таблицами сложные зависимости, и мы не планируем обращаться к каким-то полям

2024-12-09 19:18 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    private final CommentRepository commentRepository;
тоже private final можно убрать

2024-12-12 18:18 UTC, romakrnv commented on src/main/java/ru/practicum/shareit/item/entity/Item.java
> +    @ManyToOne(fetch = FetchType.LAZY)
в теории настойчиво советовали использовать Lazy, отсюда и решил добавить)
по коду в одном месте только идёт обращение к полю User, но решил на будущее сразу поправить
Спасибо за ревью!

2024-12-13 16:44 UTC, z8q approved these changes

2024-12-13 16:44 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    final UserRepository userRepository;
в FieldDefaults есть параметр makeFinal = true, то есть final тоже можно не использовать

2024-12-15 10:58 UTC, merged